import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";

export default function AppLayout({children}){
  return(
    <>
      <Head>
        <title>Maxishop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="content">
        {children}
      </div>
    </>
  )
}